export const RECEIPT_GET_REQUEST = "RECEIPT_GET_REQUEST";
export const RECEIPT_GET_SUCCESS = "RECEIPT_GET_SUCCESS";
export const RECEIPT_GET_FAIL = "RECEIPT_GET_FAIL";

export const USER_RECEIPTS_GET_REQUEST = "USER_RECEIPTS_REQUEST";
export const USER_RECEIPTS_SUCCESS = "USER_RECEIPTS_SUCCESS";
export const USER_RECEIPTS_FAIL = "USER_RECEIPTS_FAIL";

export const RECEIPT_CREATE_REQUEST = "RECEIPT_CREATE_REQUEST";
export const RECEIPT_CREATE_SUCCESS = "RECEIPT_CREATE_SUCCESS";
export const RECEIPT_CREATE_FAIL = "RECEIPT_CREATE_FAIL";
export const RECEIPT_CREATE_RESET = "RECEIPT_CREATE_RESET";

export const RECEIPT_UPDATE_REQUEST = "RECEIPT_UPDATE_REQUEST";
export const RECEIPT_UPDATE_SUCCESS = "RECEIPT_UPDATE_SUCCESS";
export const RECEIPT_UPDATE_FAIL = "RECEIPT_UPDATE_FAIL";
export const RECEIPT_UPDATE_RESET = "RECEIPT_UPDATE_RESET";

export const RECEIPT_DELETE_REQUEST = "RECEIPT_DELETE_REQUEST";
export const RECEIPT_DELETE_SUCCESS = "RECEIPT_DELETE_SUCCESS";
export const RECEIPT_DELETE_FAIL = "RECEIPT_DELETE_FAIL";
export const RECEIPT_DELETE_RESET = "RECEIPT_DELETE_RESET";
