export const SAVING_GET_REQUEST = "SAVING_GET_REQUEST";
export const SAVING_GET_SUCCESS = "SAVING_GET_SUCCESS";
export const SAVING_GET_FAIL = "SAVING_GET_FAIL";

export const USER_SAVINGS_GET_REQUEST = "USER_SAVINGS_REQUEST";
export const USER_SAVINGS_SUCCESS = "USER_SAVINGS_SUCCESS";
export const USER_SAVINGS_FAIL = "USER_SAVINGS_FAIL";

export const SAVING_CREATE_REQUEST = "SAVING_CREATE_REQUEST";
export const SAVING_CREATE_SUCCESS = "SAVING_CREATE_SUCCESS";
export const SAVING_CREATE_FAIL = "SAVING_CREATE_FAIL";
export const SAVING_CREATE_RESET = "SAVING_CREATE_RESET";

export const SAVING_UPDATE_REQUEST = "SAVING_UPDATE_REQUEST";
export const SAVING_UPDATE_SUCCESS = "SAVING_UPDATE_SUCCESS";
export const SAVING_UPDATE_FAIL = "SAVING_UPDATE_FAIL";
export const SAVING_UPDATE_RESET = "SAVING_UPDATE_RESET";

export const SAVING_DELETE_REQUEST = "SAVING_DELETE_REQUEST";
export const SAVING_DELETE_SUCCESS = "SAVING_DELETE_SUCCESS";
export const SAVING_DELETE_FAIL = "SAVING_DELETE_FAIL";
export const SAVING_DELETE_RESET = "SAVING_DELETE_RESET";

export const SAVING_DELETE_ALL_REQUEST = "SAVING_DELETE_ALL_REQUEST";
export const SAVING_DELETE_ALL_SUCCESS = "SAVING_DELETE_ALL_SUCCESS";
export const SAVING_DELETE_ALL_FAIL = "SAVING_DELETE_ALL_FAIL";
export const SAVING_DELETE_ALL_RESET = "SAVING_DELETE_ALL_RESET";

export const SAVING_ADD_AMOUNT_REQUEST = "SAVING_ADD_AMOUNT_REQUEST";
export const SAVING_ADD_AMOUNT_SUCCESS = "SAVING_ADD_AMOUNT_SUCCESS";
export const SAVING_ADD_AMOUNT_FAIL = "SAVING_ADD_AMOUNT_FAIL";
export const SAVING_ADD_AMOUNT_RESET = "SAVING_ADD_AMOUNT_RESET";
