export const TRANSACTION_GET_REQUEST = "TRANSACTION_GET_REQUEST";
export const TRANSACTION_GET_SUCCESS = "TRANSACTION_GET_SUCCESS";
export const TRANSACTION_GET_FAIL = "TRANSACTION_GET_FAIL";

export const USER_TRANSACTIONS_GET_REQUEST = "USER_TRANSACTIONS_REQUEST";
export const USER_TRANSACTIONS_SUCCESS = "USER_TRANSACTIONS_SUCCESS";
export const USER_TRANSACTIONS_FAIL = "USER_TRANSACTIONS_FAIL";

export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";
export const TRANSACTION_CREATE_RESET = "TRANSACTION_CREATE_RESET";

export const TRANSACTION_UPDATE_REQUEST = "TRANSACTION_UPDATE_REQUEST";
export const TRANSACTION_UPDATE_SUCCESS = "TRANSACTION_UPDATE_SUCCESS";
export const TRANSACTION_UPDATE_FAIL = "TRANSACTION_UPDATE_FAIL";
export const TRANSACTION_UPDATE_RESET = "TRANSACTION_UPDATE_RESET";

export const TRANSACTION_DELETE_REQUEST = "TRANSACTION_DELETE_REQUEST";
export const TRANSACTION_DELETE_SUCCESS = "TRANSACTION_DELETE_SUCCESS";
export const TRANSACTION_DELETE_FAIL = "TRANSACTION_DELETE_FAIL";
export const TRANSACTION_DELETE_RESET = "TRANSACTION_DELETE_RESET";
