import Head from "next/head";
import Logo from "../../components/Logo";
import { FaGoogle } from "react-icons/fa";
import { useState } from "react";
import Link from "next/link";
import PasswordStrengthBar from "react-password-strength-bar";

export default function RegisterPage() {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
  };

  return (
    <div className="signup-screen">
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="signup-container">
        <div className="logo-container">
          <Logo />
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
            suscipit leo a.
          </p>
        </div>

        <div className="signup-box">
          <h1>Sign Up</h1>
          <form className="signup-form" onSubmit={handleSubmit}>
            <div className="name-input">
              <div className="auth-input">
                <label htmlFor="firstName">First Name</label>
                <input
                  type="firstName"
                  id="firstName"
                  value={firstName}
                  onChange={(e) => setFirstName(e.target.value)}
                />
              </div>
              <div className="auth-input">
                <label htmlFor="lastName">Last Name</label>
                <input
                  type="lastName"
                  id="lastName"
                  value={lastName}
                  onChange={(e) => setLastName(e.target.value)}
                />
              </div>
            </div>
            <div className="auth-input">
              <label htmlFor="email">Email</label>
              <input
                type="email"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div className="auth-input">
              <label htmlFor="password">Password</label>
              <input
                type="password"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              <PasswordStrengthBar
                password={password}
                barColors={[
                  "#c9d6df",
                  "#ff6384",
                  "#ffcd56",
                  "#36a2eb",
                  "#4bc0c0",
                ]}
              />
            </div>
            <div className="auth-input">
              <label htmlFor="confirmPassword">Confirm Password</label>
              <input
                type="password"
                id="confirmPassword"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
              />
            </div>
            <button className="btn-large" type="submit">
              Sign Up
            </button>
            <button className="btn-large-dark" type="submit">
              <FaGoogle />
              <span>Sign Up With Google</span>
            </button>
          </form>

          <div className="signup-box-footer">
            <p>
              Already have an account?{"  "}
              <Link href={`/account/login`}>
                <a className="highlight-green">Login</a>
              </Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
